
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;


START TRANSACTION;
SELECT * FROM covid_cases WHERE country = 'India';
COMMIT;


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;
SELECT * FROM covid_cases WHERE confirmed > 500000;
COMMIT;